language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "speech4j"

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build --stacktrace
  - ./gradlew sonarqube --stacktrace

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'