version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tenant_db

  app:
    image: openjdk:11
    ports:
      - "8080:8080"
    volumes:
      - ./build/libs:/content-service
    command: ["java", "--enable-preview", "-jar", "/content-service/content-service-2.2.7 (SNAPSHOT).jar"]
    depends_on:
      - db