version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tenant_db
  tenant-service:
    image: speech4j/tenant-service:latest
    environment:
      - DB_URL=jdbc:postgresql://db:5432/tenant_db
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
    depends_on:
      - db
  content-service:
    image: speech4j/content-service:latest
    environment:
      - DB_URL=jdbc:postgresql://db:5432/tenant_db
      - DB_PASSWORD=postgres
      - DB_USER=postgres
    depends_on:
      - tenant-service
