spring:
  main:
    lazy-initialization: false
---
# ===============================
# Default connection pool
# ===============================
spring:
  datasource:
    hikari:
      connectionTimeout: 2000
      maximumPoolSize: 5
---
# ===============================
# DATABASE
# ===============================
db:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  name: ${DB_NAME:tenant_db}
spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    default-schema: speech4j
---
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa:show-sql: true
spring:
  jpa:
    hibernate:
      ddl-auto: none
      generate-ddl : false
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format_sql: true
        generate_statistics: false
# ===============================
# LOGGER / HIBERNATE
# ===============================
logging.level:
  org.hibernate.tool.hbm2ddl: DEBUG
  org.hibernate.SQL: DEBUG
  org.hibernate.type: TRACE
---
# ===============================
# SWAGGER
# ===============================
springdoc:
  api-docs.ath: /api-docs
  swagger-ui.path: /swagger-ui.html

remote:
  tenant-service:
    url: http://localhost:8082/tenants/

# ===============================
# S3
# ===============================
aws:
  bucketName: ${AWS_BUCKET_NAME:aws-bucket}
  endpointUrl: ${AWS_ENDPOINT_URL:aws-url}

# ===============================
# MULTIPART (MultipartProperties)
# ===============================
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 128MB
      max-request-size: 150MB

liquibase:
  master_changelog: db/changelog/db.changelog-master.yaml