# ===============================
# Default connection pool
# ===============================
spring:
  datasource:
    hikari:
      connectionTimeout: 2000
      maximumPoolSize: 5
---
# ===============================
# DATABASE
# ===============================
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db:5434/${POSTGRES_DB:content_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
---
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa:show-sql: true
spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format_sql: true
        generate_statistics: false
---
# ===============================
# SWAGGER
# ===============================
springdoc:
  api-docs.ath: /api-docs
  swagger-ui.path: /swagger-ui.html

remote:
  tenant-service:
    url: http://localhost:8082/tenants/

# ===============================
# S3
# ===============================
aws:
  accessKey: AKIA2JLHKQCPETFM4J7D
  secretKey: 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
  bucketName: speech4j-content-bucket
  endpointUrl: https://speech4j-content-bucket.s3.us-east-2.amazonaws.com/

# ===============================
# MULTIPART (MultipartProperties)
# ===============================
  # Enable multipart uploads
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 128MB
      max-request-size: 150MB