# ===============================
# Default connection pool
# ===============================
spring:
  datasource:
    hikari:
      connectionTimeout: 2000
      maximumPoolSize: 5
---
# ===============================
# DATABASE
# ===============================
db:
  driver: org.postgresql.Driver
  host: localhost
  port: 5432
  name: content_db
  url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
  username: postgres
  password: qwerty123
---
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa:show-sql: true
spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format_sql: true
        generate_statistics: false
# ===============================
# LOGGER / HIBERNATE
# ===============================
logging.level:
  org.hibernate.tool.hbm2ddl: DEBUG
  org.hibernate.SQL: DEBUG
  org.hibernate.type: TRACE
---
# ===============================
# SCHEMA-GENERATION / HIBERNATE
# ===============================
#spring:
#  jpa:
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
---
# ===============================
# SWAGGER
# ===============================
springdoc:
  api-docs.ath: /api-docs
  swagger-ui.path: /swagger-ui.html

remote:
  tenant-service:
    url: http://localhost:8082/tenants/

# ===============================
# S3
# ===============================
aws:
  accessKey: AKIA2JLHKQCPETFM4J7D
  secretKey: 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
  bucketName: speech4j-content-bucket
  endpointUrl: https://speech4j-content-bucket.s3.us-east-2.amazonaws.com/

# ===============================
# MULTIPART (MultipartProperties)
# ===============================
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 128MB
      max-request-size: 150MB